<a href="https://colab.research.google.com/github/Saru2248/Fuel/blob/main/Day5_fuel.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#sorting
import numpy as np

z = np.array([3, 1, 2])
print(np.sort(z))
print(np.sort(z)[::-1])

[1 2 3]
[3 2 1]


In [ ]:
#Random numbers
np.random.seed(0)
print(np.random.randint(1,10,5 ))
print(np.random.rand(3))
print(np.random.choice([10,20,30]))

[6 1 4 4 8]
[0.4236548  0.64589411 0.43758721]
30


In [ ]:
#create an array of number 1 to 20and print only the even number
arr = np.arange(1, 21)
even_numbers = arr[arr % 2 == 0]
print(even_numbers)

[ 2  4  6  8 10 12 14 16 18 20]


In [ ]:


#create 3*3 matrix using arrange and reshape then print rows sum and column sums
import numpy as np

matrix = np.arange(1, 10).reshape(3, 3)

print("Matrix:")
print(matrix)

print("Row sums:", np.sum(matrix, axis=1))
print("Column sums:", np.sum(matrix, axis=0))

Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Row sums: [ 6 15 24]
Column sums: [12 15 18]


In [ ]:
#Convert Celsius to Fahrenheit
import numpy as np

celsius = np.array([0, 20, 37, 100])

fahrenheit = celsius * 9 / 5 + 32

print("Celsius:", celsius)
print("Fahrenheit:", fahrenheit)

Celsius: [  0  20  37 100]
Fahrenheit: [ 32.   68.   98.6 212. ]


In [ ]:
#Apply a 10% discount to prices above 500 in an array using np.where
import numpy as np

prices = np.array([200, 450, 600, 800, 1000])

discounted = np.where(prices > 500, prices * 0.90, prices)

print("Original prices:", prices)
print("Final prices:", discounted)

Original prices: [ 200  450  600  800 1000]
Final prices: [200. 450. 540. 720. 900.]


In [ ]:
#Generate 10 random integers from 1 to 100 using seed 7 and print the mean, maximum, minimum, and sorted array.
import numpy as np

np.random.seed(7)

arr = np.random.randint(1, 101, 10)

print("Array:", arr)
print("Mean:", np.mean(arr))
print("Maximum:", np.max(arr))
print("Minimum:", np.min(arr))
print("Sorted array:", np.sort(arr))

Array: [48 69 26 68 84 24 93 58 15 24]
Mean: 50.9
Maximum: 93
Minimum: 15
Sorted array: [15 24 24 26 48 58 68 69 84 93]


In [ ]:
#normalize an array using (x-min)/(max-min)
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

normalized = (arr - np.min(arr)) / (np.max(arr) - np.min(arr))

print("Original array:", arr)
print("Normalized array:", normalized)

Original array: [10 20 30 40 50]
Normalized array: [0.   0.25 0.5  0.75 1.  ]


In [ ]:
#find the mean and standard deviation of an array of marks
import numpy as np

marks = np.array([70, 80, 85, 90, 95])

mean = np.mean(marks)
std_dev = np.std(marks)

print("Marks:", marks)
print("Mean:", mean)
print("Standard Deviation:", std_dev)


Marks: [70 80 85 90 95]
Mean: 84.0
Standard Deviation: 8.602325267042627


In [ ]:
#Replace all negativde values in an array with 0
import numpy as np

arr = np.array([10, -5, 20, -8, 30, -2])

arr[arr < 0] = 0

print("Updated array:", arr)


Updated array: [10  0 20  0 30  0]


In [ ]:
#compare the time taken by a list and a numpy array to add 1,000,000 number
import numpy as np
import time

numbers_list = list(range(1000000))
numbers_array = np.arange(1000000)


start = time.time()
list_result = [x + 1 for x in numbers_list]
list_time = time.time() - start


start = time.time()
array_result = numbers_array + 1
array_time = time.time() - start

print(f"List time: {list_time:.6f} seconds")
print(f"NumPy array time: {array_time:.6f} seconds")

if array_time > 0:
    print(f"NumPy is {list_time / array_time:.2f} times faster")


List time: 0.056653 seconds
NumPy array time: 0.003758 seconds
NumPy is 15.07 times faster


In [2]:
import numpy as np

# Take student names as input
names = []

for i in range(5):
    name = input(f"Enter name of student {i + 1}: ")
    names.append(name)

# Take marks for 3 subjects
marks = []

for i in range(5):
    print(f"\nEnter marks for {names[i]}:")
    s1 = float(input("Subject 1: "))
    s2 = float(input("Subject 2: "))
    s3 = float(input("Subject 3: "))

    marks.append([s1, s2, s3])

# Convert lists into NumPy arrays
names = np.array(names)
marks = np.array(marks)

# 1. Total and average of each student
total = np.sum(marks, axis=1)
average = np.mean(marks, axis=1)

print("\n--- Student Results ---")

for i in range(5):
    print(f"{names[i]}: Total = {total[i]}, Average = {average[i]:.2f}")

# 2. Find the topper
topper_index = np.argmax(total)

print(f"\nTopper: {names[topper_index]}")
print(f"Total Marks: {total[topper_index]}")

# 3. Average marks of each subject
subject_average = np.mean(marks, axis=0)

print("\n--- Subject Averages ---")
print(f"Subject 1: {subject_average[0]:.2f}")
print(f"Subject 2: {subject_average[1]:.2f}")
print(f"Subject 3: {subject_average[2]:.2f}")

# 4. Count students who passed all subjects
passed_all = np.all(marks >= 50, axis=1)
pass_count = np.sum(passed_all)

print(f"\nStudents who passed all subjects: {pass_count}")

# 5. Assign grades using np.where()
grades = np.where(
    average >= 90, "A",
    np.where(average >= 75, "B",
    np.where(average >= 50, "C", "F"))
)

print("\n--- Student Grades ---")

for i in range(5):
    print(f"{names[i]}: {grades[i]}")

Enter name of student 1: 10
Enter name of student 2: 25
Enter name of student 3: 60
Enter name of student 4: 48
Enter name of student 5: 79

Enter marks for 10:
Subject 1: 44
Subject 2: 555
Subject 3: 77

Enter marks for 25:
Subject 1: 24
Subject 2: 22
Subject 3: 20

Enter marks for 60:
Subject 1: 50
Subject 2: 55
Subject 3: 45

Enter marks for 48:
Subject 1: 11
Subject 2: 55
Subject 3: 77

Enter marks for 79:
Subject 1: 44
Subject 2: 55
Subject 3: 99

--- Student Results ---
10: Total = 676.0, Average = 225.33
25: Total = 66.0, Average = 22.00
60: Total = 150.0, Average = 50.00
48: Total = 143.0, Average = 47.67
79: Total = 198.0, Average = 66.00

Topper: 10
Total Marks: 676.0

--- Subject Averages ---
Subject 1: 34.60
Subject 2: 148.40
Subject 3: 63.60

Students who passed all subjects: 0

--- Student Grades ---
10: A
25: F
60: C
48: F
79: C


In [6]:
#series
import pandas as pd

s = pd.Series([10, 20, 30], index=["a", "b", "c"])

print(s)

print(s["b"])
print(s.mean())

a    10
b    20
c    30
dtype: int64
20
20.0


In [9]:
#dataframe from dict
import pandas as pd

data = {
    "Name": ["Sarthak", "Rahul", "Amit"],
    "Age": [21, 22, 20],
    "City": ["Sambhajinagar", "Pune", "Mumbai"]
}

df = pd.DataFrame(data)

print(df)

      Name  Age           City
0  Sarthak   21  Sambhajinagar
1    Rahul   22           Pune
2     Amit   20         Mumbai


In [12]:
import pandas as pd

df = pd.read_csv("student_data.csv")

print(df)
print(df.head())

[Error] 'student_data.csv' not found. Please upload it to the Colab files panel on the left.


In [15]:
import pandas as pd
from google.colab import files
uploaded = files.upload()
filename = list(uploaded.keys())[0]
df = pd.read_csv(filename)


print(df)

Saving student_data_1000 (1).csv to student_data_1000 (1).csv
    Student_ID          Name  Age  Gender       City                 Course  \
0      STU0001   Isha Sharma   19   Other     Nagpur                    BBA   
1      STU0002    Diya Gupta   18  Female    Solapur                    MCA   
2      STU0003   Aditi Verma   20    Male  Hyderabad                    BCA   
3      STU0004    Meera Mane   20    Male     Nagpur             B.Tech CSE   
4      STU0005  Ishaan Kadam   24   Other     Nagpur  B.Sc Computer Science   
..         ...           ...  ...     ...        ...                    ...   
995    STU0996    Aarav More   20   Other    Jalgaon                  B.Com   
996    STU0997    Diya Patil   21  Female   Kolhapur  B.Sc Computer Science   
997    STU0998   Aditya More   21    Male     Mumbai                    MCA   
998    STU0999   Sana Sharma   20  Female  Bengaluru             B.Tech CSE   
999    STU1000   Rohan Mehta   22  Female      Latur                 

In [16]:
print(df.shape)
print(list(df.columns))
print(df.dtypes)

(1000, 11)
['Student_ID', 'Name', 'Age', 'Gender', 'City', 'Course', 'Python_Marks', 'SQL_Marks', 'Math_Marks', 'Total_Marks', 'Attendance_Percent']
Student_ID            object
Name                  object
Age                    int64
Gender                object
City                  object
Course                object
Python_Marks           int64
SQL_Marks              int64
Math_Marks             int64
Total_Marks            int64
Attendance_Percent     int64
dtype: object


In [17]:
print(df.describe)

<bound method NDFrame.describe of     Student_ID          Name  Age  Gender       City                 Course  \
0      STU0001   Isha Sharma   19   Other     Nagpur                    BBA   
1      STU0002    Diya Gupta   18  Female    Solapur                    MCA   
2      STU0003   Aditi Verma   20    Male  Hyderabad                    BCA   
3      STU0004    Meera Mane   20    Male     Nagpur             B.Tech CSE   
4      STU0005  Ishaan Kadam   24   Other     Nagpur  B.Sc Computer Science   
..         ...           ...  ...     ...        ...                    ...   
995    STU0996    Aarav More   20   Other    Jalgaon                  B.Com   
996    STU0997    Diya Patil   21  Female   Kolhapur  B.Sc Computer Science   
997    STU0998   Aditya More   21    Male     Mumbai                    MCA   
998    STU0999   Sana Sharma   20  Female  Bengaluru             B.Tech CSE   
999    STU1000   Rohan Mehta   22  Female      Latur                    BBA   

     Python_Marks

In [18]:
print(df.info)

<bound method DataFrame.info of     Student_ID          Name  Age  Gender       City                 Course  \
0      STU0001   Isha Sharma   19   Other     Nagpur                    BBA   
1      STU0002    Diya Gupta   18  Female    Solapur                    MCA   
2      STU0003   Aditi Verma   20    Male  Hyderabad                    BCA   
3      STU0004    Meera Mane   20    Male     Nagpur             B.Tech CSE   
4      STU0005  Ishaan Kadam   24   Other     Nagpur  B.Sc Computer Science   
..         ...           ...  ...     ...        ...                    ...   
995    STU0996    Aarav More   20   Other    Jalgaon                  B.Com   
996    STU0997    Diya Patil   21  Female   Kolhapur  B.Sc Computer Science   
997    STU0998   Aditya More   21    Male     Mumbai                    MCA   
998    STU0999   Sana Sharma   20  Female  Bengaluru             B.Tech CSE   
999    STU1000   Rohan Mehta   22  Female      Latur                    BBA   

     Python_Marks  

In [20]:

print(df["Name"])
print(df[["Name", "Python_Marks", "SQL_Marks", "Math_Marks"]])

0       Isha Sharma
1        Diya Gupta
2       Aditi Verma
3        Meera Mane
4      Ishaan Kadam
           ...     
995      Aarav More
996      Diya Patil
997     Aditya More
998     Sana Sharma
999     Rohan Mehta
Name: Name, Length: 1000, dtype: object
             Name  Python_Marks  SQL_Marks  Math_Marks
0     Isha Sharma            60         56          53
1      Diya Gupta            79         29          28
2     Aditi Verma            50         94          78
3      Meera Mane            68         60          44
4    Ishaan Kadam            69         58          30
..            ...           ...        ...         ...
995    Aarav More            27         40          64
996    Diya Patil            42         72          88
997   Aditya More            81         67          42
998   Sana Sharma            54         67          68
999   Rohan Mehta            53         73          91

[1000 rows x 4 columns]


In [24]:
import pandas as pd

print(df.loc[0])
print(df.loc[0:4, ["Name", "Age", "City"]])

Student_ID                STU0001
Name                  Isha Sharma
Age                            19
Gender                      Other
City                       Nagpur
Course                        BBA
Python_Marks                   60
SQL_Marks                      56
Math_Marks                     53
Total_Marks                   169
Attendance_Percent             89
Name: 0, dtype: object
           Name  Age       City
0   Isha Sharma   19     Nagpur
1    Diya Gupta   18    Solapur
2   Aditi Verma   20  Hyderabad
3    Meera Mane   20     Nagpur
4  Ishaan Kadam   24     Nagpur


In [26]:
print(df.iloc[0:2, 0:2])
print(df.iloc[2,2])

  Student_ID         Name
0    STU0001  Isha Sharma
1    STU0002   Diya Gupta
20


In [27]:
print(df[df["SQL_Marks"] >= 70])

    Student_ID           Name  Age  Gender       City                 Course  \
2      STU0003    Aditi Verma   20    Male  Hyderabad                    BCA   
5      STU0006      Sana Nair   18  Female    Solapur                  B.Com   
6      STU0007      Diya More   24   Other     Nanded              B.Tech IT   
11     STU0012    Nisha Gupta   19   Other      Akola             B.Tech CSE   
12     STU0013  Isha Kulkarni   23    Male     Jaipur  B.Sc Computer Science   
..         ...            ...  ...     ...        ...                    ...   
991    STU0992  Riya Deshmukh   18  Female    Jalgaon                    BCA   
992    STU0993   Manav Jadhav   21  Female     Jaipur                    BCA   
994    STU0995    Aditi Reddy   25   Other    Solapur                    MCA   
996    STU0997     Diya Patil   21  Female   Kolhapur  B.Sc Computer Science   
999    STU1000    Rohan Mehta   22  Female      Latur                    BBA   

     Python_Marks  SQL_Marks  Math_Mark

In [ ]:

Latur_top = df[(df["City"] == "Latur") & (df["Total_Marks"] > 75)]
print(Latur_top)

In [41]:
df["result"] = np.where(df["Total_Marks"] >= 50, "Pass", "Fail")
df["score_out_of_80"] = df["Total_Marks"] / 10

print(df[["Name", "Total_Marks", "result", "score_out_of_80"]])

             Name  Total_Marks result  score_out_of_80
0     Isha Sharma          169   Pass             16.9
1      Diya Gupta          136   Pass             13.6
2     Aditi Verma          222   Pass             22.2
3      Meera Mane          172   Pass             17.2
4    Ishaan Kadam          157   Pass             15.7
..            ...          ...    ...              ...
995    Aarav More          131   Pass             13.1
996    Diya Patil          202   Pass             20.2
997   Aditya More          190   Pass             19.0
998   Sana Sharma          189   Pass             18.9
999   Rohan Mehta          217   Pass             21.7

[1000 rows x 4 columns]
